version: '3'
services:
  web:
    image: nginx:1.18-alpine
    depends_on:
      - app
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - ./docker/web/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html/
  app:
    image: php:7.4-fpm-alpine
    depends_on:
      - db
      - mailhog
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/pho.ini:ro
      - ./:/var/www/html/:cached
  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_PORT:-8025}:8025

volumes:
  db-data:
